# Generated by Django 5.1.3 on 2024-12-09 17:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product_analytics', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salesrecord',
            name='product',
        ),
        migrations.DeleteModel(
            name='ProductEngagement',
        ),
        migrations.DeleteModel(
            name='Product',
        ),
        migrations.DeleteModel(
            name='SalesRecord',
        ),
    ]
