# Generated by Django 5.1.3 on 2024-12-09 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('user_id', models.IntegerField()),
                ('category_id', models.IntegerField()),
                ('name', models.CharField(max_length=255)),
                ('stock', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_purchased', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'cart',
                'managed': True,
            },
        ),
    ]
