# Generated by Django 5.1.3 on 2024-11-23 01:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('financial_analytics', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salesdata',
            name='product',
        ),
        migrations.DeleteModel(
            name='Product',
        ),
        migrations.DeleteModel(
            name='SalesData',
        ),
    ]
