# Generated by Django 5.1.3 on 2024-12-09 17:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales_analytics', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Sale',
        ),
    ]
